---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: quote-host
  namespace: ambassador
spec:
  hostname: quote.starter-kit.online
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory
    email: quote@gmail.com
  tlsSecret:
    name: tls2-cert
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080
