apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: monitoring
data:
  blackbox.yml: |
    modules:
      health_check:
        prober: http
        timeout: 5s
        valid_http_status_codes: []
        method: GET
        url: "{{ .URL }}"